import { useTheme } from "../theme/useTheme";

// Presentation metadata for stop types currently generated by the planner.
const STOP_STYLE = {
  FUEL_STOP: {
    label: "Fuel",
    badge: "border-[#fed7aa] bg-[#fff7ed] text-[#c2410c]",
  },
  REST_STOP: {
    label: "Rest",
    badge: "border-[#bfdbfe] bg-[#eff6ff] text-[#075aaa]",
  },
  BREAK_STOP: {
    label: "Break",
    badge: "border-[#bbf7d0] bg-[#f0fdf4] text-[#166534]",
  },
};

/**
 * Displays the ordered list of HOS-driven stops for the generated route.
 *
 * Expected stop shape:
 * - type: planner stop category, such as FUEL_STOP, REST_STOP, or BREAK_STOP
 * - day/hour: scheduled point in the trip plan
 * - duration_hours: stop length shown to dispatch users
 */
export default function StopsTimeline({ stops }) {
  const { theme } = useTheme();

  return (
    <section className={`${theme.card} xl:max-h-163.5 xl:overflow-auto`}>
      <div className="flex items-start justify-between gap-4">
        <div>
          <h2 className={theme.sectionTitle}>Stops timeline</h2>
          <p className={theme.sectionSubtitle}>
            Required breaks and service events generated from HOS assumptions.
          </p>
        </div>
        <span className={theme.pill}>{stops.length} stops</span>
      </div>

      {stops.length === 0 ? (
        <div className="mt-5 rounded-md border border-[#bbf7d0] bg-[#f0fdf4] p-4 text-sm font-semibold text-[#166534]">
          No intermediate fuel or rest stops are required for this route.
        </div>
      ) : (
        <div className="mt-6 space-y-4">
          {stops.map((stop, index) => {
            // Keep unknown backend stop types readable instead of dropping the badge.
            const style = STOP_STYLE[stop.type] ?? {
              label: stop.type.replaceAll("_", " ").toLowerCase(),
              badge: "border-[#d9e0e8] bg-white text-[#3e4c59]",
            };

            return (
              <div key={`${stop.type}-${stop.day}-${stop.hour}-${index}`} className="flex gap-3">
                <div className="flex flex-col items-center">
                  <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-[#17202a] text-sm font-semibold text-white shadow-sm">
                    {index + 1}
                  </div>

                  {/* Omit the trailing connector so the timeline ends cleanly. */}
                  {index !== stops.length - 1 && (
                    <div className="mt-2 h-full min-h-8 w-px bg-[#d9e0e8]" />
                  )}
                </div>

                <div className={`min-w-0 flex-1 ${theme.mutedCard}`}>
                  <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                    <div className="min-w-0">
                      <span className={`inline-flex rounded-md border px-2.5 py-1 text-xs font-semibold capitalize ${style.badge}`}>
                        {style.label}
                      </span>
                      <p className="mt-3 font-semibold text-[#17202a]">
                        Day {stop.day}, hour {stop.hour}
                      </p>
                      <p className="mt-1 text-sm leading-6 text-[#637083]">
                        Scheduled compliance stop
                      </p>
                    </div>

                    <span className="w-fit rounded-md border border-[#d9e0e8] bg-white px-3 py-2 text-xs font-semibold text-[#3e4c59] shadow-sm">
                      {stop.duration_hours} hrs
                    </span>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </section>
  );
}
